# Use root/example as user/password credentials
version: '3.1'

services:

  node-server:
    # ตั้งชื่อ container (เหมือน --name)
    container_name: node-server
    command: node --watch ./dist/server
    build: . # ตำแหน่ง dockerfile
    restart: always
    ports:
      - "8000:8000" # map port ออกมา เหมือน -p ใน docker run 

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sirisoft
      MONGO_INITDB_ROOT_PASSWORD: sirisoft

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sirisoft
      ME_CONFIG_MONGODB_ADMINPASSWORD: sirisoft
      ME_CONFIG_MONGODB_URL: mongodb+srv://sirisoft:sirisoft@cluster0.akdvwvx.mongodb.net/ 
